### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by Voziv** [argocd-diff-action/argocd-diff-action#4] opened 2023-02-28 21:20 UTC
I haven't had time to do an exact reproduction on a fresh argocd install, however either `ApplicationSet` or argocd `2.6.x` seems to have broken this action for ratehub.

```
Run ratehub/argocd-diff-action@v0
  with:
    argocd-server-fqdn: *** (dev instance, running v2.6.1)
    argocd-token: ***
    github-token: ***
    argocd-version: v2.6.1
    argocd-extra-cli-args: --grpc-web
```

When running the action I get `TypeError: Cannot read properties of undefined (reading 'source')`. It's not helpful in debugging what is going wrong. If it's a result of the api call I'd like to have the api call contents dumped.

I believe I've already added a bit more debug logs but some of them were not successful in dumping enough information.

**Comment by morey-tech** [comment] 2023-03-20 20:48
@Voziv, can you re-run one of the failed workflows for the action with debug logging enabled and post the logs here?
![Xnapper-2023-03-20-16 46 55](https://user-images.githubusercontent.com/4213435/226462259-4bc42ead-40ac-4a0a-ba38-49abe2863667.png)

**Comment by Voziv** [comment] 2023-03-23 13:51
Here's the log archive of my latest run with debug logging turned on: [logs_349.zip](https://github.com/argocd-diff-action/argocd-diff-action/files/11051299/logs_349.zip)

The most notable bit that I can see is

```
##[debug]Making API call to: 'argocd.dev.ratehub.dev/api/v1/applications'
{ metadata: { name: 'abhay-ratehub-frontend' } }
TypeError: Cannot read properties of undefined (reading 'source')
Error: TypeError: Cannot read properties of undefined (reading 'source')
    at /home/runner/work/_actions/ratehub/argocd-diff-action/v0/dist/index.js:13473:29
    at Array.filter (<anonymous>)
    at AppCollection.filterByRepo (/home/runner/work/_actions/ratehub/argocd-diff-action/v0/dist/index.js:13471:44)
    at /home/runner/work/_actions/ratehub/argocd-diff-action/v0/dist/index.js:13875:14
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/ratehub/argocd-diff-action/v0/dist/index.js:13771:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
##[debug]Node Action run completed with exit code 1
```

**Comment by chancez** [comment] 2024-02-19 23:28
So I looked into it, and it seems like the problem is the `fields` selection logic. After I fixed that, I also noticed it failed on multi-source repos. I have a branch you can see here with the changes I made to fix this: https://github.com/chancez/argocd-diff-action/pull/1

**Comment by Voziv** [comment] 2024-02-25 19:42
Thanks for looking into it @chancez. If I can manage to get some time :crossed_fingers: I want to look into getting this fixed and some type of automated testing that I can run so that this can be a bit easier to maintain and update.

**Comment by fcrespofastly** [comment] 2024-02-25 21:39
Hey folks!

I tested @chancez branch and it seems the issue went away, though I'm hitting something different now:

```
time="2024-02-25T21:35:40Z" level=fatal msg="rpc error: code = Unknown desc = error receiving manifest file stream: error receiving tgz file: file checksum validation error: calc e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 sent d56dcb6cc50a6605b73b72e9f41d63f8959d8b61b72e9f9bad6b947f45b402be"
```

**Comment by fcrespofastly** [comment] 2024-02-25 21:59
Ok, when removing `--server-side-generate` it just worked!

**Comment by fcrespofastly** [comment] 2024-03-06 13:17
@Voziv hey 👋🏻 !

Any chance we can get this merged?

**Comment by pshelby** [comment] 2024-12-16 16:31
@chancez 's branch worked for me as well, thank you!  Would be great to merge that to the original repo.

**Comment by Voziv** [comment] 2024-12-20 18:35
I'm working on this today

**Closed** 2024-12-20 22:04 UTC
